"""Add ONDELETE clause

Revision ID: 02923f056907
Revises: bca5d73c8775
Create Date: 2021-12-05 21:29:40.003937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02923f056907'
down_revision = 'bca5d73c8775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_membership_ibfk_1', 'chat_membership', type_='foreignkey')
    op.drop_constraint('chat_membership_ibfk_2', 'chat_membership', type_='foreignkey')
    op.create_foreign_key(None, 'chat_membership', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_membership', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_membership', type_='foreignkey')
    op.drop_constraint(None, 'chat_membership', type_='foreignkey')
    op.create_foreign_key('chat_membership_ibfk_2', 'chat_membership', 'user', ['user_id'], ['id'])
    op.create_foreign_key('chat_membership_ibfk_1', 'chat_membership', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###
