"""Add a many-to-many in seen_by

Revision ID: 6fc2f69af661
Revises: 895625b4e503
Create Date: 2021-12-19 18:04:37.393741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fc2f69af661'
down_revision = '895625b4e503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_views',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.drop_constraint('message_ibfk_3', 'message', type_='foreignkey')
    op.drop_column('message', 'seen_user_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('seen_user_ids', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_ibfk_3', 'message', 'user', ['seen_user_ids'], ['id'])
    op.drop_table('message_views')
    # ### end Alembic commands ###
