"""Set up hierarchy

Revision ID: 895625b4e503
Revises: de500eedf7aa
Create Date: 2021-12-13 17:09:42.725189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895625b4e503'
down_revision = 'de500eedf7aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=False),
    sa.Column('seen_user_ids', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seen_user_ids'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
