"""Update chat type enumeration

Revision ID: bca5d73c8775
Revises: 2784ddf4a8ea
Create Date: 2021-11-23 18:53:06.427524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bca5d73c8775'
down_revision = '2784ddf4a8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', '_member_limit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('_member_limit', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
