"""Add last_online and message views

Revision ID: de500eedf7aa
Revises: 62fa184e02fb
Create Date: 2021-12-11 18:04:01.717436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de500eedf7aa'
down_revision = '62fa184e02fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('message', 'datetime')
    op.add_column('user', sa.Column('last_online', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_online')
    op.add_column('message', sa.Column('datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('message', 'created_at')
    # ### end Alembic commands ###
